#!/usr/bin/env ruby

require 'aws/s3'
include AWS::S3

Base.establish_connection!(
  :access_key_id     => ENV['AWS_ID'],
  :secret_access_key => ENV['AWS_SECRET']
)

# アップロード
S3Object.store(
  ARGV[1],       # s3 path
  open(ARGV[2]), # local file path
  ARGV[0],       # Bucket name
  'x-amz-acl' => 'public-read'
)
