#!/usr/bin/env ruby

require 'aws/s3'
include AWS::S3

Base.establish_connection!(
  :access_key_id     => ENV['AWS_ID'],
  :secret_access_key => ENV['AWS_SECRET'],
  :server => "#{ARGV[0]}.s3.amazonaws.com"
)

# アップロード
S3Object.store(
  ARGV[1],       # アップロード先のファイル名
  open(ARGV[2]), # アップロードしたいローカルファイル
  ARGV[0]        # バケット名
)
